### ISSUE TITLE
Get on the Awesome list

### ISSUE THREAD

**Issue by houstdav000** [vitejs/awesome-vite#135]
Given there is a list of all lists, I'd recommend trying to get on it: [the Awesome list](https://github.com/sindresorhus/awesome). There is already a [pull request](https://github.com/sindresorhus/awesome/pull/1970) out there to get added to the list, but this list isn't fully compliant.

There are a couple of requirements, a lot of which using the [awesome-lint](https://github.com/sindresorhus/awesome-lint) and its [GitHub Action](https://github.com/sindresorhus/awesome-lint#github-actions) can help resolve.

However, some, such as changing the default branch from `master` to `main`, must be done by repository administrators.

Otherwise, it looks like a great opportunity overall.

**Comment by stingalleman** [comment]
I need to make a PR that follows the Awesome guidelines, but I'm really busy at the moment. I'll do it asap but it might take a while. If anybody wants to do this, feel free!

**Comment by antfu** [comment]
Keep track on https://github.com/sindresorhus/awesome/pull/1970, closing
