### ISSUE TITLE
Remove/Deprecate/Archive plugins like vite-eslint

### ISSUE THREAD

**Issue by Shinigami92** [vitejs/awesome-vite#245]
Should outdated and not maintained plugins be marked somehow? So the search for a plugin is a bit easier?

**Comment by Scrum** [comment]
> Should outdated and not maintained plugins be marked somehow? So the search for a plugin is a bit easier?

yes if not updated for more than 6 months

**Comment by Shinigami92** [comment]
Oh so in this case I just was around 1-2 weeks to early 😄
