### ISSUE TITLE
If I have a starter template but it has only Chinese doc, can I add it?

### ISSUE THREAD

**Issue by Jiaocz** [vitejs/awesome-vite#454]
Because may Chinese doc could help some Chinese speakings get started faster, so should I add it now or later when I have a translation of English?

Previous pr: #453 [ovx](https://github.com/ovx-js/ovx)

**Comment by Scrum** [comment]
@Jiaocz Not everyone will be able to know a language other than the international one.

**Comment by Jiaocz** [comment]
@Scrum OK I will make a translation, then reopen that pr

**Comment by Jiaocz** [comment]
@Scrum OK I will make a translation, then reopen that pr
