### ISSUE TITLE
How would I go about a lesser known library integration?

### ISSUE THREAD

**Issue by amoutonbrady** [vitejs/awesome-vite#47]
Hey, comming from [https://github.com/vitejs/vite/pull/1404](https://github.com/vitejs/vite/pull/1404), I was wondering how would I go about adding my plugin for [solid-js](https://github.com/ryansolid/solid)?

As much as I would like to say this is among the most popular libraries, this isn't quite there yet. I was just wondering if I should follow the pattern of the other libraries like

### Plugins for solid

- my plugin

Or if you'd rather have something like "other integrations"?

Just want to be sure I don't miss anything there. CONTRIBUTING.md didn't really outlined that :)

Thanks!

**Comment by antfu** [comment]
I am ok with it and it looks kinda cool. I think maybe it's better to make the header a link so that people can have a quicker understanding of what it is.

Like

```md
## [Solid](https://github.com/ryansolid/solid)

...
```

**Comment by amoutonbrady** [comment]
Alright, that's awesome, thanks for the quick answer, really appreciate it! :)
