### ISSUE TITLE
Can we add 'https://github.com/maifeeulasad/react-pipeline' under react group?

### ISSUE THREAD

**Issue by maifeeulasad** [vitejs/awesome-vite#531]
Does this project has all the credibility to be included?

[https://github.com/maifeeulasad/react-pipeline](https://github.com/maifeeulasad/react-pipeline)

This is a deployment-ready boilerplate, using:
 - React
 - TS
 - AntD
 - Vite
 - Tailwind

This can be a good push for the beginners, who want to run.

Ready to send a PR.

**Comment by Scrum** [comment]
Yes, if there are no analogues in the current list

**Comment by maifeeulasad** [comment]
@Scrum, I have added my repo. Let me know if it needs anything. Thanks/
