### ISSUE TITLE
Add Dockerized: ViteJS+ TailwindCSS + HandlebarsJS

### ISSUE THREAD

**Issue by dendrofen** [vitejs/awesome-vite#642]
I've constructed frontend stack with docker compose, please add this to list.
Hope this would be usefully to community 💻

https://github.com/dendrofen/docker-vitejs-tailwind-handlebars

Also there is no-docker version for this build:

https://github.com/dendrofen/vitejs-tailwind-handlebars

**Comment by Scrum** [comment]
welcome a PR
