### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [vitejs/awesome-vite#734]
Hi, I found a few broken hyperlinks:

- [ ] https://github.com/time4dev/vite-esbuild-typescript-checker (file: README.md, status code: 404)
- [ ] https://github.com/vitejs/vite/tree/main/packages/plugin-vue (file: README.md, status code: 404)
- [ ] https://github.com/vitejs/vite/tree/main/packages/plugin-vue-jsx (file: README.md, status code: 404)
- [ ] https://github.com/vitejs/vite/tree/main/packages/plugin-react (file: README.md, status code: 404)
- [ ] https://github.com/nrwl/nx/tree/master/packages/cra-to-nx (file: README.md, status code: 404)

**Comment by Scrum** [comment]
PR a welcome
