### ISSUE TITLE
 The repo should be at least 30 days old

### ISSUE THREAD

**Issue by szoradigeza** [vitejs/awesome-vite#751]
When I tried to open a PR I saw this point in the checklist.
The repo should be at least 30 days old. 

I'm just curious what the point of this is?

Thanks, in advance!

**Comment by HugoImaios** [comment]
From what I saw in the merged PR, the rule seems not mandatory

**Comment by Jogai** [comment]
To prevent submissions that are hacked together in a day and never looked after anymore

**Comment by HugoImaios** [comment]
IMO the rule should be more strictly used
