### ISSUE TITLE
GitHub changed layout of readme document header? ToC is on the right.

### ISSUE THREAD

**Issue by junaga** [vitejs/awesome-vite#815]
> Use the "Table of Contents" menu on the top-left corner to explore the list.

The Table of Contents icons if on the top-right for my client, not top-left.

![image](https://github.com/vitejs/awesome-vite/assets/35770913/f008d2a1-6a5e-4108-a5fc-848046b09c23)

**Comment by Scrum** [comment]
@junaga thanks

**Comment by junaga** [comment]
no @Scrum thank you guys. May Vite live forever.
