### ISSUE TITLE
Add plugin unplugin-detect-duplicated-deps

### ISSUE THREAD

**Issue by tjx666** [vitejs/awesome-vite#842]
https://unplugin-detect-duplicated-deps.vercel.app/introduction.html

![image](https://github.com/vitejs/awesome-vite/assets/41773861/3388df1e-46c6-427d-a0f1-1546cad8c827)

**Comment by Scrum** [comment]
welcome a PR

**Comment by tjx666** [comment]
> welcome a PR

https://github.com/vitejs/awesome-vite/pull/850

**Comment by Scrum** [comment]
done
