### ISSUE TITLE
Add vite-plugin-pretty-module-classnames

### ISSUE THREAD

**Issue by teplostanski** [vitejs/awesome-vite#880]
Description: Adds the filename without the -module suffix to the class names of CSS modules.

Npm: https://www.npmjs.com/package/vite-plugin-pretty-module-classnames

Repo: https://github.com/teplostanski/vite-plugin-pretty-module-classnames

**Comment by Scrum** [comment]
Welcome

**Comment by teplostanski** [comment]
> Welcome

???

**Comment by Scrum** [comment]
> > Welcome
> 
> ???

PR a welcome

**Comment by teplostanski** [comment]
> > > Welcome
> > 
> > 
> > ???
> 
> PR a welcome

[#885](https://github.com/vitejs/awesome-vite/pull/885)
