### ISSUE TITLE
Add mindplay/php-vite (a Vite integration for PHP with no dependencies)

### ISSUE THREAD

**Issue by mindplay-dk** [vitejs/awesome-vite#886]
I'm unsure where to add this, but I wrote a "vanilla" PHP package that makes it easy to integrate Vite with PHP:

https://github.com/mindplay-dk/php-vite

There is an example MPA project as well:

https://github.com/mindplay-dk/php-vite-mpa

Unlike the other listed PHP packages, this isn't tied to any framework - it's just a Composer package, you can use it anywhere.

I don't know why this didn't seem to exist. 🙂

**Comment by Scrum** [comment]
welcome a PR

**Comment by mindplay-dk** [comment]
Sorry, I think I forgot to ask my actual question. 😄

Where should it be listed?

The subsections of "Integrations with backend" is a bit confusing, as it's a mix of languages and frameworks.

Should I just create a new section titled "PHP", since there isn't one?

And where should I add it? The entries aren't alphabetized. Which I'd be happy to do while I'm at it, if you'd like?

I'd also be happy to reorganize that whole section by language, if you'd like?

**Comment by mindplay-dk** [comment]
Submitted a PR to just add it for now - I'd still like to help reorganize this (and update the issue templates) if you'd like.
