### ISSUE TITLE
Add "vite-react-neutralino-template"

### ISSUE THREAD

**Issue by Bonnev** [vitejs/awesome-vite#899]
Hi! A while back I made a template for Vite + React.js + Neutralino for desktop apps. I would love to contribute to this list with it! Link: https://github.com/Bonnev/vite-react-neutralino-template

**Comment by Scrum** [comment]
Welcome a PR

**Comment by Bonnev** [comment]
@Scrum Thanks! Here is the PR: https://github.com/vitejs/awesome-vite/pull/900
