### ISSUE TITLE
Squash merge PR

### ISSUE THREAD

**Issue by nlemoine** [vitejs/awesome-vite#935]
Hey,

I come quite often to check out newly added packages and since it's a just a README file, it's not easy to check what's new. The way to check this is having a look at commit history. Unfortunately, the PR merged in this repo are merged using merge commits, which makes it "harder/slower" to read:

![Capture d’écran 2024-08-28 à 14 30 01](https://github.com/user-attachments/assets/8a201535-2bbb-4b61-8c98-c24cdd98b505)

Could you use "Squash/Rebase merge" 🙏? You'll have a cleaner git history and GitHub will remember your choices so you don't have to select it each time.

**Comment by Scrum** [comment]
I understand your pain, but it seems better to use the github api to build a list by date with the ability to sort

**Comment by nlemoine** [comment]
Thanks for your feedback!
