### ISSUE TITLE
Please update logo.

### ISSUE THREAD

**Issue by atilkan** [vitejs/awesome-vite#94]
Vite has new logo. Current one looks more like vue.

**Comment by antfu** [comment]
Would you like to draft a design? Thanks

**Comment by atilkan** [comment]
Is this ok?

<img width="443" alt="Screen Shot 2021-02-17 at 05 00 03" src="https://user-images.githubusercontent.com/68614829/108145750-05a95980-70dd-11eb-8a9a-381e46ad6892.png">

**Comment by antfu** [comment]
not sure, maybe let the thunder on top of the glasses? Or maybe we would need another way to integrate them together.

**Comment by atilkan** [comment]
Ok, i am not a designer. I am not going to do 1px down, 2px up thing.

**Comment by atilkan** [comment]
Good call.
