### ISSUE TITLE
react-pwa doesn't work on Windows because of semicolon in filename

### ISSUE THREAD

**Issue by platonicLiquid** [vitejs/awesome-vite#948]
Git checkout fails when cloning to a Windows machine. Not sure what the solution is here as the author seems resistant to fixing the problem.<sup>1</sup>

1. [git checkout fails on Windows due to file name .github/workflows/tests:e2e.yml](https://github.com/suren-atoyan/react-pwa/issues/59)

**Comment by Scrum** [comment]
Doesn't look like a topic for this repository
