### ISSUE TITLE
Can `ViteDevServerLauncher` be embedded in a .net process?

### ISSUE THREAD

**Issue by myderr** [vitejs/awesome-vite#977]
I observed that the following code is used to start vite now
```
        var startInfo = new ProcessStartInfo(command, args)
        {
            CreateNoWindow = false,
            UseShellExecute = true,
            WindowStyle = ProcessWindowStyle.Normal,
            WorkingDirectory = Path.GetFullPath(workingDirectory),
        };
```
If UseShellExecute is set to false and the input and output streams are managed, can a dos window be reduced and IsViteDevelopmentServerRunning can also be removed? because vite has been started and stopped with the main process
```
        var startInfo = new ProcessStartInfo("node", args)
        {
            CreateNoWindow = true,
            UseShellExecute = false,
            RedirectStandardInput = true,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            WindowStyle = ProcessWindowStyle.Hidden, 
            WorkingDirectory = Path.GetFullPath(workingDirectory),
        };
```
For example, the following figure shows that I cannot stop Vite when it stops, so I cannot submit a pull request.
![image](https://github.com/user-attachments/assets/d05e95fd-171c-4c93-98d8-bb115b77354c)

**Comment by myderr** [comment]
Sent to the wrong warehouse

**Comment by Jogai** [comment]
https://www.nuget.org/packages/Proggmatic.SpaServices.Vite#readme-body-tab
